#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cleanCase0

rm -rf constant/polyMesh

rm -rf constant/C
rm -rf constant/Cx
rm -rf constant/Cy
rm -rf constant/Cz

#------------------------------------------------------------------------------
